#@see http://hoserdude.com/2014/06/19/spring-boot-configurationproperties-and-profile-management-using-yaml/
spring:
  profiles.active: dev
---
spring:
  profiles: dev
ldap:
  url: ldap://localhost:10389
  userOn: uid=admin,ou=system
  password: secret
db:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/eip_rushucloud
  username: root
  password: 
# Specify the DBMS
jpa:
  database: MYSQL
# Show or not log for each sql query
  show-sql: true
# Hibernate settings are prefixed with spring.jpa.hibernate.*
hibernate:
  ddl-auto: update
  dialect: org.hibernate.dialect.MySQL5Dialect
  naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy 
---
spring:
  profiles: test
ldap:
  url: ldap://182.92.232.131:389
  userOn: cn=admin,dc=182,dc=92,dc=232,dc=131
  password: rushu0915
db:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/eip_rushucloud
  username: root
  password:  
# DataSource settings: set here configurations for the database connection
# datasource:
#   url: jdbc:mysql://localhost:3306/eip_rushucloud
#   username: root
#   password: 
#   driverClassName: com.mysql.jdbc.Driver
# Specify the DBMS
jpa:
  database: MYSQL
# Show or not log for each sql query
  show-sql: true
# Hibernate settings are prefixed with spring.jpa.hibernate.*
hibernate:
  ddl-auto: update
  dialect: org.hibernate.dialect.MySQL5Dialect
  naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy  