#@see http://hoserdude.com/2014/06/19/spring-boot-configurationproperties-and-profile-management-using-yaml/
spring:
  profiles.active: test
---
spring:
  profiles: dev
ldap:
  url: ldap://localhost:10389
  userOn: uid=admin,ou=system
  password: secret
upload:
  folder: uploads/
---
spring:
  profiles: test
ldap:
  url: ldap://123.57.78.65:389
  userOn: cn=Manager,dc=123,dc=57,dc=78,dc=65
  password: Kit7740321
upload:
  folder: uploads/
---
spring:
  profiles: stage
ldap:
  url: ldap://123.56.112.163:389
  userOn: cn=admin,dc=123,dc=56,dc=112,dc=163
  password: Rushu0915
upload:
  folder: uploads/